const data ={
    products:[
        {
            name:'Nike Slim Shirt',
            slug:'nike-slim-shirt',
            category:'Shirts',
            image:'/images/nike-shirt.jpg',
            price: 120,
            countInStock: 10,
            brand:'Nike',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Adidas Fit Shirt',
            slug:'adidas-slim-shirt',
            category:'Shirts',
            image:'/images/adidas-shirt.jpg',
            price: 250,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name:'Nike Slim Pant',
            slug:'nike-slim-pant',
            category:'Pants',
            image:'/images/nike-pants.jpg',
            price: 25,
            countInStock: 15,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name:'Adidas Fit Pant',
            slug:'adidas-slim-pant',
            category:'Pants',
            image:'/images/adidas-pants.jpg',
            price: 65,
            countInStock: 5,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ]
}
export default data